# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: C# bot

on:
  push:
    # branches: [ "main", "debug-workflow" ]
    paths: ["**.cs", ".github/workflows/bot.yml"]
  pull_request:
    # branches: [ "main" ]
    paths: ["**.cs", ".github/workflows/bot.yml"]

defaults:
 run:
  working-directory: ./Bot

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Build
      run: dotnet publish -c Release -r linux-arm64 --no-self-contained
    - name: Upload program
      uses: actions/upload-artifact@v3
      with:
        name: Bot
        path: |
          Bot/bin/Release/net8.0/linux-arm64
          !Bot/bin/Release/net8.0/linux-arm64/*.pdb
          !Bot/bin/Release/net8.0/linux-arm64/publish
  inspect:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      id: setup-dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.101
    - name: Restore
      run: dotnet restore
    - name: Inspect
      uses: muno92/resharper_inspectcode@v1
      with:
        workingDirectory: './Bot'
        solutionPath: './Bot.sln'
        noBuild: true
        minimumSeverity: 'warning'
        dotnetVersion: ${{ steps.setup-dotnet.outputs.dotnet-version }}